---
layout: post
title: "Multi-band Structure"
date:   2015-10-23 12:00:0
authors: "Jason Williams, Jeff Hollister, Kristina Riemer, Mike Smorul, Zack Brym"
dateCreated:  2015-10-23 12:00:00
lastModified: 2015-10-23 12:00:00
category: spatio-temporal-workshop
tags: [module-1]
mainTag: GIS-Spatial-Data
description: "This post expands on raster principles and functions in R for multi-band files."
code1: 
image:
  feature: lidar_GrandMesa.png
  credit: LiDAR data collected over Grand Mesa, Colorado - National Ecological Observatory Network (NEON)
  creditlink: http://www.neoninc.org
permalink: /R/Raster-Data-In-R/
code1: /R/2015-07-22-Introduction-to-Raster-Data-In-R.R
comments: true

---

<section id="table-of-contents" class="toc">
  <header>
    <h3>Contents</h3>
  </header>
<div id="drawer" markdown="1">
*  Auto generated table of contents
{:toc}
</div>
</section><!-- /#table-of-contents -->

##About
This activity will walk you through the fundamental principles of working 
with raster data in R.

**R Skill Level:** Intermediate - you've got the basics of `R` down.

<div id="objectives">

<h3>Goals / Objectives</h3>
After completing this activity, you will know:
<ol>
<li>How a raster file stores multiple bands.</li>
<li>How to import multi-band rasters into `R` using the `raster` library.</li>
<li>How to plot multi-band rasters in `R`.</li>
</ol>

<h3>Things You'll Need To Complete This Lesson</h3>

<h3>R Libraries to Install:</h3>
<ul>
<li><strong>raster:</strong> <code> install.packages("raster")</code></li>
<li><strong>rgdal:</strong> <code> install.packages("rgdal")</code></li>

</ul>
<h4>Tools To Install</h4>

Please be sure you have the most current version of `R` and preferably
R studio to write your code.


<h4>Data to Download</h4>

Download the workshop data:
<ul>
<li><a href="http://figshare.com/articles/NEON_AOP_Hyperspectral_Teaching_Dataset_SJER_and_Harvard_forest/1580086" class="btn btn-success"> DOWNLOAD Sample NEON LiDAR data in Raster Format & Vegetation Sampling Data</a></li>
</ul>

<p>The LiDAR and imagery data used to create the rasters in this dataset were 
collected over the Harvard and San Joaquin field sites 
and processed at <a href="http://www.neoninc.org" target="_blank" >NEON </a> 
headquarters. The entire dataset can be accessed by request from the NEON website.</p>  

<h4>Recommended Pre-Lesson Reading</h4>
<ul>
<li>
<a href="http://cran.r-project.org/web/packages/raster/raster.pdf" target="_blank">
Read more about the `raster` package in R.</a>
</li>
</ul>
</div>

```
# Read in multi-band raster with raster function, the default is the first band
RGB_band1 <- raster("~/Documents/Graduate_School/Workshops/GST_hackathon/1_WorkshopData/NEON_RemoteSensing/HARV/HARV_RGB_Ortho.tif")
plot(RGB_band1) #Point out dimension, CRS, and values attributes, but esp. band
RGB_band1

# Can specify which band you want to read in
RGB_band2 <- raster("~/Documents/Graduate_School/Workshops/GST_hackathon/1_WorkshopData/NEON_RemoteSensing/HARV/HARV_RGB_Ortho.tif", band = 2
plot(RGB_band2)
RGB_band2

# Use stack function to read in all bands
RGB <- stack("~/Documents/Graduate_School/Workshops/GST_hackathon/1_WorkshopData/NEON_RemoteSensing/HARV/HARV_RGB_Ortho.tif")
RGB #Look at dimensions, CRS, and min/max
#Metadata file? 
plot(RGB)

# The plotRGB function plots all bands together, is an image like our eyes would see
plotRGB(RGB, r = 1, g = 2, b = 3)

#The black bands on the edges are zeros but should be NAs, might want to show 
#them how to turn them into NAs? 

# TODO: Challenge: calculate NDVI, but would need an infrared band to do this
```